name:                grus-grus
version:             0.1.0.0
github:              "rotifyld/grus-grus"
license:             BSD3
author:              "Dawid Borys"
maintainer:          "db394094"
copyright:           "2019 Dawid Borys"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/grus-grus#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- mtl

library:
  source-dirs:
    - .

executables:
  interpreter:
    main:                Main.hs
    source-dirs:
      - app
      - src
      - src/bnfc
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    dependencies:
    - grus-grus
